version: '3.8'

services:
  web:
    container_name: tehspec_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=False
    expose:
      - 8000
    command: gunicorn --bind 0.0.0.0:8000 portfolio_site.wsgi:application

  nginx:
    container_name: tehspec_nginx
    image: nginx:alpine
    ports:
      - "8092:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web