# Generated by Django 5.2.5 on 2025-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('USER_INFO', 'User Information'), ('SOCIAL_LINKS', 'Social Links'), ('CONTENT', 'Content')], help_text='Configuration block (e.g., USER_INFO)', max_length=50)),
                ('key', models.CharField(help_text='Configuration key (e.g., PORTFOLIO_NAME)', max_length=100)),
                ('value', models.TextField(help_text='Configuration value')),
            ],
            options={
                'verbose_name': 'Portfolio Configuration',
                'verbose_name_plural': 'Portfolio Configurations',
                'unique_together': {('block', 'key')},
            },
        ),
    ]
