# Generated by Django 5.2.5 on 2025-08-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_options_project_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
