# Generated by Django 5.2.5 on 2025-08-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short',
            field=models.CharField(blank=True, verbose_name='Кратко'),
        ),
    ]
