# Generated by Django 5.2.5 on 2025-08-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('issuer', models.CharField(max_length=200, verbose_name='Организация')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на сертификат')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order'],
            },
        ),
    ]
